const body = document.querySelector("body");
const dark = document.querySelector("#dark");
const cont = document.querySelector(".container");
const html = document.querySelector("html");
const navbar = document.querySelector(".navbar");
const nav = document.querySelector(".nav");
const inp = document.querySelector("#inp");
const nameEl = document.querySelector("#name");
const form = document.querySelector("#form");
const aytilishi = document.querySelector("#aytilishi");
const audeo = document.querySelector("#audeo");
const imag = document.querySelector("#imag")
const noneMean = document.querySelector("#noneMean")
const synonemm =document.querySelector("#synonem")
const verbMean =document.querySelector("#verbMean")
